## 🔹 Section 1: Basics & Series (Q1–Q20)

### Q1. Create a Pandas Series from a list of integers.
> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

In [2]:
import pandas as pd
l=pd.Series([10,20,30,40,50])
print(l)
print(type(l))

0    10
1    20
2    30
3    40
4    50
dtype: int64
<class 'pandas.core.series.Series'>

### Q2. Create a Series from a dictionary with custom index.
> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

In [5]:
d={
    "Name": 'Vikas',
    "Marks":90,
    "Age":25
}
dic=pd.Series(d)
print(dic)

Name     Vikas
Marks       90
Age         25
dtype: object

### Q3. Access elements using index labels.
> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

In [9]:
l=pd.Series(
    [1,2,3,4,5],
    index=['a','b','c','d','e']
)
print(l)
print(l["a"])
print(l[['b','c']])
print(l["a":"e"])

a    1
b    2
c    3
d    4
e    5
dtype: int64
1
b    2
c    3
dtype: int64
a    1
b    2
c    3
d    4
e    5
dtype: int64

### Q4. Perform arithmetic operations on a Series.
> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

In [13]:
import pandas as pd
l=pd.Series([10,20,30,40,50])
print(l)
print("*"*50)
print("Addition :\n", l + 5)
print("*"*50)
print("Subtraction :\n", l - 5)
print("*"*50)
print("Multiplication :\n", l * 5)
print("*"*50)
print("Division :\n", l / 5)
print("*"*50)
print("Floor Division : \n ", l // 5 )
print("*"*50)
print("Modulus : \n ", l % 5)
print("*"*50)
print("Power : \n ", l ** 2)

0    10
1    20
2    30
3    40
4    50
dtype: int64
**************************************************
Addition :
 0    15
1    25
2    35
3    45
4    55
dtype: int64
**************************************************
Subtraction :
 0     5
1    15
2    25
3    35
4    45
dtype: int64
**************************************************
Multiplication :
 0     50
1    100
2    150
3    200
4    250
dtype: int64
**************************************************
Division :
 0     2.0
1     4.0
2     6.0
3     8.0
4    10.0
dtype: float64
**************************************************
Floor Division :
  0     2
1     4
2     6
3     8
4    10
dtype: int64
**************************************************
Modulus :
  0    0
1    0
2    0
3    0
4    0
dtype: int64
**************************************************
Power :
  0     100
1     400
2     900
3    1600
4    2500
dtype: int64

### Q5. Find mean, min, max of a Series.
> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

In [17]:
l=pd.Series([10,20,30,40,50])
print(l)
print("Mean:", l.mean())
print("Min :", l.min())
print("Max :", l.max())
print("Sum :", l.sum())
print("Median :", l.median())
print("Std :", l.std())

0    10
1    20
2    30
3    40
4    50
dtype: int64
Mean: 30.0
Min : 10
Max : 50
Sum : 150
Median : 30.0
Std : 15.811388300841896

### Q6. Apply conditional filtering on a Series.
> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

In [3]:
import pandas as pd
l = pd.Series([25, 60, 45, 80, 90])
print(l[l > 50])
print(l[(l > 40) & (l < 90)])
print(l[(l < 30) | (l > 80)])

1    60
3    80
4    90
dtype: int64
1    60
2    45
3    80
dtype: int64
0    25
4    90
dtype: int64

### Q7. Replace values in a Series.
> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

In [7]:
l=pd.Series([10,20,30,40,50])
l_rep=l.replace(20,99)
print(l_rep)

0    10
1    99
2    30
3    40
4    50
dtype: int64

### Q8. Convert Series data type.
> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

In [8]:
s=pd.Series([10,20,30])
s_f=s.astype(float)
print(s_f)
print(s_f.dtype)

0    10.0
1    20.0
2    30.0
dtype: float64
float64

### Q9. Check for null values in Series.
> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

In [9]:
import pandas as pd
import numpy as np
s = pd.Series([10, np.nan, 30, np.nan, 50])
print(s.isnull())

0    False
1     True
2    False
3     True
4    False
dtype: bool

### Q10. Fill missing values in Series.
> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

In [14]:
import pandas as pd
import numpy as np
s=pd.Series([10,np.nan,30,np.nan,50])
s_fill=s.fillna(0)
print(s_fill)
print("*"*50)
mean_val=s.mean()
s_filled=s.fillna(mean_val)
print(s_filled)
print("*"*50)
print(s.ffill())

0    10.0
1     0.0
2    30.0
3     0.0
4    50.0
dtype: float64
**************************************************
0    10.0
1    30.0
2    30.0
3    30.0
4    50.0
dtype: float64
**************************************************
0    10.0
1    10.0
2    30.0
3    30.0
4    50.0
dtype: float64

### Q11. Create DataFrame from a list.
> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

In [16]:
data=[
    ["Vikas",25,90],
    ["Rahul",22,85],
    ["Amit",24,88]
]
df=pd.DataFrame(data,columns=["Name","Age","Marks"])
print(df)

    Name  Age  Marks
0  Vikas   25     90
1  Rahul   22     85
2   Amit   24     88

### Q12. Create DataFrame from a dictionary.
> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

In [18]:
data={
    "Name":["Vikas","Rahul","Amit"],
    "Age":[25,22,24],
    "Marks":[90,85,88]
}
df=pd.DataFrame(data)
print(df)

    Name  Age  Marks
0  Vikas   25     90
1  Rahul   22     85
2   Amit   24     88

### Q13. Create DataFrame from list of dictionaries.
> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

In [19]:
data=[
    {"Name":"Vikas","Age":25,"Marks":90},
    {"Name":"Rahul","Age":22,"Marks":95},
    {"Name":"Amit","Age":27,"Marks":93}
]
df=pd.DataFrame(data)
print(df)

    Name  Age  Marks
0  Vikas   25     90
1  Rahul   22     95
2   Amit   27     93

### Q14. Display DataFrame structure (shape, columns, dtypes).
> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

In [20]:
print(df.shape)
print(df.columns)
print(df.dtypes)
print(df.info())
print(df.describe())

(3, 3)
Index(['Name', 'Age', 'Marks'], dtype='object')
Name     object
Age       int64
Marks     int64
dtype: object
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    3 non-null      object
 1   Age     3 non-null      int64
 2   Marks   3 non-null      int64
dtypes: int64(2), object(1)
memory usage: 204.0+ bytes
None
             Age      Marks
count   3.000000   3.000000
mean   24.666667  92.666667
std     2.516611   2.516611
min    22.000000  90.000000
25%    23.500000  91.500000
50%    25.000000  93.000000
75%    26.000000  94.000000
max    27.000000  95.000000

### Q15. Select single column from DataFrame.
> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

In [22]:
df[["Name"]]

    Name
0  Vikas
1  Rahul
2   Amit

### Q16. Select multiple columns.
> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

In [23]:
print(df[["Name","Marks"]])

    Name  Marks
0  Vikas     90
1  Rahul     95
2   Amit     93

### Q17. Add new column with scalar value.
> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

In [26]:
df["Bonus"]=10
print(df)

    Name  Age  Marks  Bonus
0  Vikas   25     90     10
1  Rahul   22     95     10
2   Amit   27     93     10

### Q18. Add column using Series.
> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

In [27]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit"]
})
salary = pd.Series([50000, 60000, 55000])
df["Salary"] = salary
print(df)

    Name  Salary
0  Vikas   50000
1  Rahul   60000
2   Amit   55000

### Q19. Rename columns using `rename()`.
> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

In [29]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul"],
    "Marks": [90, 85]
})
new_df = df.rename(columns={"Marks": "Score"})
print(new_df)

    Name  Score
0  Vikas     90
1  Rahul     85

### Q20. Rename multiple columns.
> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

In [30]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul"],
    "Age": [25, 22],
    "Marks": [90, 85]
})
new_df = df.rename(columns={
    "Name": "Student_Name",
    "Marks": "Score"
})
print(new_df)

  Student_Name  Age  Score
0        Vikas   25     90
1        Rahul   22     85

## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

### Q21. Select rows using `loc`.
> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

In [3]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit", "Sneha"],
    "Marks": [90, 85, 78, 95],
    "Age": [25, 24, 23, 22]
}, index=["A", "B", "C", "D"])

print(df)
print("*"*50)
#select single row
print(df.loc["A"])
print("*"*50)
#select multiple rows using range
print(df.loc["A":"C"])

    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23
D  Sneha     95   22
**************************************************
Name     Vikas
Marks       90
Age         25
Name: A, dtype: object
**************************************************
    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23
**************************************************

### Q22. Select rows using `iloc`.
> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

In [6]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit", "Sneha"],
    "Marks": [90, 85, 78, 95],
    "Age": [25, 24, 23, 22]
})

print(df)
print("*"*50)
#select single row
print(df.iloc[0])
print("*"*50)
#select third row
print(df.iloc[2])
print("*"*50)
#select multiple rows using slicing
print(df.iloc[1:4])

    Name  Marks  Age
0  Vikas     90   25
1  Rahul     85   24
2   Amit     78   23
3  Sneha     95   22
**************************************************
Name     Vikas
Marks       90
Age         25
Name: 0, dtype: object
**************************************************
Name     Amit
Marks      78
Age        23
Name: 2, dtype: object
**************************************************
    Name  Marks  Age
1  Rahul     85   24
2   Amit     78   23
3  Sneha     95   22

### Q23. Access specific row and column.
> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

In [8]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit"],
    "Marks": [90, 85, 78],
    "Age": [25, 24, 23]
}, index=["A", "B", "C"])

print(df)
print(df.loc["B", "Marks"])
print(df.loc["C", "Age"])
print(df.iloc[1, 1])

    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23
85
23
85

### Q24. Select subset using multiple rows & columns.
> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

In [11]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit", "Sneha"],
    "Marks": [90, 85, 78, 95],
    "Age": [25, 24, 23, 22]
}, index=["A", "B", "C", "D"])

print(df)
print(df.loc[["A", "C"], ["Name", "Marks"]])
print(df.loc[["B", "D"], ["Name"]])

    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23
D  Sneha     95   22
    Name  Marks
A  Vikas     90
C   Amit     78
    Name
B  Rahul
D  Sneha

### Q25. Apply conditional filtering using `loc`.
> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

In [13]:
import pandas as pd

df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit", "Sneha"],
    "Marks": [90, 85, 78, 95],
    "Age": [25, 24, 23, 22]
})

print(df)
print(df.loc[df["Marks"] > 80])
df.loc[df["Marks"] > 80]
print(df.loc[df["Marks"] > 80, ["Name", "Marks"]])
print(df.loc[df["Age"] > 23])
print(df.loc[(df["Marks"] > 80) & (df["Age"] > 23)])
print(df.loc[(df["Marks"] > 90) | (df["Age"] < 23)])

    Name  Marks  Age
0  Vikas     90   25
1  Rahul     85   24
2   Amit     78   23
3  Sneha     95   22
    Name  Marks  Age
0  Vikas     90   25
1  Rahul     85   24
3  Sneha     95   22
    Name  Marks
0  Vikas     90
1  Rahul     85
3  Sneha     95
    Name  Marks  Age
0  Vikas     90   25
1  Rahul     85   24
    Name  Marks  Age
0  Vikas     90   25
1  Rahul     85   24
    Name  Marks  Age
3  Sneha     95   22

### Q26. Slice rows using index range.
> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

In [6]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit", "Sneha", "Neha"],
    "Marks": [90, 85, 78, 95, 88],
    "Age": [25, 24, 23, 22, 21]
}, index=["A", "B", "C", "D", "E"])

print(df)
print("*"*50)
#position based slicing using iloc
print(df.iloc[1:4])
print("*"*50)
#first 3 rows
print(df.iloc[0:3])
print("*"*50)
#labeled base slicing using loc
print(df.loc["B":"D"])

    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23
D  Sneha     95   22
E   Neha     88   21
**************************************************
    Name  Marks  Age
B  Rahul     85   24
C   Amit     78   23
D  Sneha     95   22
**************************************************
    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23
**************************************************
    Name  Marks  Age
B  Rahul     85   24
C   Amit     78   23
D  Sneha     95   22

### Q27. Slice columns using labels.
> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

In [10]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit"],
    "Marks": [90, 85, 78],
    "Age": [25, 24, 23],
    "City": ["Mumbai", "Pune", "Delhi"]
})

print(df)
print("*"*50)
#select columns name to age
print(df.loc[:, "Name":"Age"])
print("*"*50)
#select marks to city
print(df.loc[:, "Marks":"City"])
print("*"*50)
#select all columns
print(df.loc[:, :])

    Name  Marks  Age    City
0  Vikas     90   25  Mumbai
1  Rahul     85   24    Pune
2   Amit     78   23   Delhi
**************************************************
    Name  Marks  Age
0  Vikas     90   25
1  Rahul     85   24
2   Amit     78   23
**************************************************
   Marks  Age    City
0     90   25  Mumbai
1     85   24    Pune
2     78   23   Delhi
**************************************************
    Name  Marks  Age    City
0  Vikas     90   25  Mumbai
1  Rahul     85   24    Pune
2   Amit     78   23   Delhi

### Q28. Slice columns using position.
> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

In [14]:
#select columns from position 1 to 2
print(df.iloc[:, 1:3])
print("*"*50)
#select first two columns
print(df.iloc[:, 0:2])

   Marks  Age
0     90   25
1     85   24
2     78   23
**************************************************
    Name  Marks
0  Vikas     90
1  Rahul     85
2   Amit     78

### Q29. Perform combined row & column slicing.
> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

In [16]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit", "Sneha", "Neha"],
    "Marks": [90, 85, 78, 95, 88],
    "Age": [25, 24, 23, 22, 21],
    "City": ["Mumbai", "Pune", "Delhi", "Chennai", "Bangalore"]
})

print(df)
print("*"*50)
#using loc
print(df.iloc[0:3, 0:2])
print("*"*50)
#select specfic rows and columns
print(df.iloc[[0, 3, 4], [0, 2]])

    Name  Marks  Age       City
0  Vikas     90   25     Mumbai
1  Rahul     85   24       Pune
2   Amit     78   23      Delhi
3  Sneha     95   22    Chennai
4   Neha     88   21  Bangalore
**************************************************
    Name  Marks
0  Vikas     90
1  Rahul     85
2   Amit     78
**************************************************
    Name  Age
0  Vikas   25
3  Sneha   22
4   Neha   21

### Q30. Set a column as index.
> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

In [18]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit"],
    "Marks": [90, 85, 78],
    "Age": [25, 24, 23]
})

print(df)
print("*"*50)
#set name as index
df2 = df.set_index("Name")
print(df2)
print("*"*50)
print(df2.loc["Vikas"])

    Name  Marks  Age
0  Vikas     90   25
1  Rahul     85   24
2   Amit     78   23
**************************************************
       Marks  Age
Name
Vikas     90   25
Rahul     85   24
Amit      78   23
**************************************************
Marks    90
Age      25
Name: Vikas, dtype: int64

### Q31. Create hierarchical index (MultiIndex).
> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

In [24]:
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR"],
    "Name": ["Vikas", "Rahul", "Amit", "Sneha"],
    "Salary": [50000, 60000, 55000, 58000]
})

print(df)
print("*"*50)
#Creating multiindex
df2 = df.set_index(["Department", "Name"])
print(df2)
print("*"*50)
#accessing data using multiindex
print(df2.loc[("IT", "Vikas")])

  Department   Name  Salary
0         IT  Vikas   50000
1         IT  Rahul   60000
2         HR   Amit   55000
3         HR  Sneha   58000
**************************************************
                  Salary
Department Name
IT         Vikas   50000
           Rahul   60000
HR         Amit    55000
           Sneha   58000
**************************************************
Salary    50000
Name: (IT, Vikas), dtype: int64

### Q32. Reset index.
> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

In [4]:
import pandas as pd
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit"],
    "Marks": [90, 85, 78]
})
df = df.set_index("Name")
print(df)
print("*"*50)
df.reset_index(inplace=True)
print(df)

       Marks
Name
Vikas     90
Rahul     85
Amit      78
**************************************************
    Name  Marks
0  Vikas     90
1  Rahul     85
2   Amit     78

### Q33. Reset multi-index.
> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

In [3]:
df = pd.DataFrame({
    "Department": ["IT", "IT", "HR", "HR"],
    "Name": ["Vikas", "Rahul", "Amit", "Sneha"],
    "Salary": [50000, 60000, 55000, 58000]
})
df = df.set_index(["Department", "Name"])
print(df)
print("*"*50)
df2 = df.reset_index()
print(df2)

                  Salary
Department Name
IT         Vikas   50000
           Rahul   60000
HR         Amit    55000
           Sneha   58000
**************************************************
  Department   Name  Salary
0         IT  Vikas   50000
1         IT  Rahul   60000
2         HR   Amit   55000
3         HR  Sneha   58000

### Q34. Convert index to column.
> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

In [6]:
df = pd.DataFrame({
    "Marks": [90, 85, 78]
},
index=["Vikas", "Rahul", "Amit"])
print(df)
df2 = df.reset_index()
print(df2)

       Marks
Vikas     90
Rahul     85
Amit      78
   index  Marks
0  Vikas     90
1  Rahul     85
2   Amit     78

### Q35. Use drop option in `reset_index`.
> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

In [8]:
df = pd.DataFrame({
    "Marks": [90, 85, 78]
},
index=["Vikas", "Rahul", "Amit"])
print(df)
print(df.reset_index())
print(df.reset_index(drop=True))

       Marks
Vikas     90
Rahul     85
Amit      78
   index  Marks
0  Vikas     90
1  Rahul     85
2   Amit     78
   Marks
0     90
1     85
2     78

### Q36. Perform label-based indexing.
> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

In [10]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit"],
    "Marks": [90, 85, 78],
    "Age": [25, 24, 23]
}, index=["A", "B", "C"])

print(df)
print(df.loc["A"])
print(df.loc[["A", "C"]])
print(df.loc["A":"C"])

    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23
Name     Vikas
Marks       90
Age         25
Name: A, dtype: object
    Name  Marks  Age
A  Vikas     90   25
C   Amit     78   23
    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23

### Q37. Perform position-based indexing.
> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

In [11]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit"],
    "Marks": [90, 85, 78],
    "Age": [25, 24, 23]
}, index=["A", "B", "C"])

print(df)
print(df.iloc[0])
print(df.iloc[1])
print(df.iloc[[0, 2]])
print(df.iloc[0:2])

    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24
C   Amit     78   23
Name     Vikas
Marks       90
Age         25
Name: A, dtype: object
Name     Rahul
Marks       85
Age         24
Name: B, dtype: object
    Name  Marks  Age
A  Vikas     90   25
C   Amit     78   23
    Name  Marks  Age
A  Vikas     90   25
B  Rahul     85   24

### Q38. Access first N rows.
> 💡 **Hint:** `df.head(N)` — default N is 5.

In [13]:
df = pd.DataFrame({
    "Name": ["Vikas", "Rahul", "Amit", "Sneha", "Neha", "Ravi", "Priya"],
    "Marks": [90, 85, 78, 95, 88, 82, 91]
})
print(df.head(3))

    Name  Marks
0  Vikas     90
1  Rahul     85
2   Amit     78

### Q39. Access last N rows.
> 💡 **Hint:** `df.tail(N)` — default N is 5.

In [14]:
print(df.tail())

    Name  Marks
2   Amit     78
3  Sneha     95
4   Neha     88
5   Ravi     82
6  Priya     91

### Q40. Extract random sample from DataFrame.
> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

In [15]:
print(df.sample(n=3))

    Name  Marks
2   Amit     78
6  Priya     91
0  Vikas     90

## 🔹 Section 3: Data Cleaning (Q41–Q60)

In [34]:
import pandas as pd
import numpy as np

df = pd.DataFrame({
    " Employee ID ": [101, 102, 103, 104, 105, 105],
    "Name": [" Vikas ", "RAHUL", "sneha", np.nan, "Ankit@123", "Ankit@123"],
    "Gender": ["Male","male ","FEMALE","Female","M","M"],
    "Department": ["IT","HR",np.nan,"Finance","IT","IT"],
    "Salary": [50000,60000,np.nan,55000,999999, 999999],
    "Age": [25,"26","Twenty Seven",29,np.nan,np.nan ],
    "Email": ["vikas@gmail.com","rahul@yahoo.com","sneha@hotmail.com",np.nan,"ankit@company.com","ankit@company.com"],
    "City": [" Mumbai ","mumbai","PUNE","Chennai","Bangalore","Bangalore"]
})
print(df)

    Employee ID        Name  Gender Department    Salary           Age  \
0            101     Vikas     Male         IT   50000.0            25
1            102      RAHUL   male          HR   60000.0            26
2            103      sneha  FEMALE        NaN       NaN  Twenty Seven
3            104        NaN  Female    Finance   55000.0            29
4            105  Ankit@123       M         IT  999999.0           NaN
5            105  Ankit@123       M         IT  999999.0           NaN

               Email       City
0    vikas@gmail.com    Mumbai
1    rahul@yahoo.com     mumbai
2  sneha@hotmail.com       PUNE
3                NaN    Chennai
4  ankit@company.com  Bangalore
5  ankit@company.com  Bangalore

### Q41. Detect missing values using `isnull()`.
> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

In [18]:
print(df.isnull())
print(df.isnull().sum())
print(df.isnull().any())

    Employee ID    Name  Gender  Department  Salary    Age  Email   City
0          False  False   False       False   False  False  False  False
1          False  False   False       False   False  False  False  False
2          False  False   False        True    True  False  False  False
3          False   True   False       False   False  False   True  False
4          False  False   False       False   False   True  False  False
5          False  False   False       False   False   True  False  False
 Employee ID     0
Name             1
Gender           0
Department       1
Salary           1
Age              2
Email            1
City             0
dtype: int64
 Employee ID     False
Name              True
Gender           False
Department        True
Salary            True
Age               True
Email             True
City             False
dtype: bool

### Q42. Drop missing values using `dropna()`.
> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

In [33]:
#drop rows having at least one missing value
df.dropna()
#store result back
df = df.dropna()
#drop columns having missing values
df.dropna(axis=1)

,Employee ID,Name,Gender,Department,Salary,Age,Email,City
0,101,Vikas,Male,IT,50000.0,25,vikas@gmail.com,Mumbai
1,102,RAHUL,male,HR,60000.0,26,rahul@yahoo.com,mumbai